# Generated by Django 4.1.5 on 2023-01-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandGraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slr_by_year', models.ImageField(upload_to='stats_img/', verbose_name='Динамика ЗП по годам')),
                ('count_vac_by_year', models.ImageField(upload_to='stats_img/', verbose_name='Количество вакансий по годам')),
                ('slr_by_year_name', models.ImageField(upload_to='stats_img/', verbose_name='Динамика ЗП указанной профессии по годам')),
                ('count_vac_by_year_name', models.ImageField(upload_to='stats_img/', verbose_name='Количество вакансий по годам для указанной профессии')),
            ],
        ),
    ]
