# Generated by Django 4.1.5 on 2023-01-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPageEls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slr_by_year', models.ImageField(upload_to='stats_img/', verbose_name='Динамика ЗП по годам')),
                ('count_vac_by_year', models.ImageField(upload_to='stats_img/', verbose_name='Количество вакансий по годам')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
        migrations.CreateModel(
            name='GeographyPageEls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slr_by_cities', models.ImageField(upload_to='stats_img/', verbose_name='Динамика ЗП по городам')),
                ('count_vac_by_cities', models.ImageField(upload_to='stats_img/', verbose_name='Количество вакансий по городам')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
        migrations.CreateModel(
            name='KeySkillsPageEls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slr_by_cities', models.ImageField(upload_to='stats_img/', verbose_name='Динамика ЗП по городам')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageEls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название профессии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='vac_img/', verbose_name='Изображение')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
        migrations.DeleteModel(
            name='DemandGraphs',
        ),
    ]
