# Generated by Django 4.1.5 on 2023-01-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_stats', '0003_alter_keyskillspageels_slr_by_cities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyskillspageels',
            old_name='slr_by_cities',
            new_name='key_skills_img',
        ),
    ]
