# Generated by Django 4.1.5 on 2023-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_stats', '0006_remove_mainpageels_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandpageels',
            name='description_1',
            field=models.TextField(default=None, verbose_name='Описание рисунка 1'),
        ),
        migrations.AddField(
            model_name='demandpageels',
            name='description_2',
            field=models.TextField(default=None, verbose_name='Описание рисунка 2'),
        ),
        migrations.AddField(
            model_name='demandpageels',
            name='description_3',
            field=models.TextField(default=None, verbose_name='Описание рисунка 3'),
        ),
    ]
